name: CI

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, World!"
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        run: ls -lah
      - name: step-2
        run: whoami
      - name: step-3
        run: hostname
      - name: step-4
        run: tree
      - name: step-5
        run: pwd


