name: CI

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.set_output.outputs.my-var }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Say Hello
        id: set_output
        run: echo "my_var=HelloFromJob1"  >> $GITHUB_OUTPUT
      - name: test var
        run: echo "echo $my_var"
      - name: test Env Var
        run: set

  Build:
    runs-on: ubuntu-latest
    needs: say-hello
    steps:
      - name: Step-1
        run: ls -lah
      - name: step-2
        run: whoami
      - name: step-3
        run: hostname
      - name: step-4
        run: tree
      - name: step-5
        run: pwd
      - name: Get Variable From prev. Job
        run: echo "The Var is ${{ needs.say-hello.outputs.my_var }}"


