name: File test

on:
  push:
    branches:
      - main

jobs:
  CreateFile:
    runs-on: ubuntu-latest
    steps:
    - name: Create File
      run: echo "Create file" >> ./myfile.txt
    - name: List file 1
      run: ls -lah
    - name: List File 2
      run: ls -lah ./
    - uses: actions/upload-artifact@v4
      with:
        name: mydata
        path: ./myfile.txt