name: File download test

on:
  workflow_run:
    workflows: ["File test"]
    types:
      - completed

jobs:
  CreateFile:
    runs-on: ubuntu-latest
    needs: CreateFile
    steps:
    - name: List file Pre
      run: ls -lah
    - uses: actions/download-artifact@v4
      with:
        name: mydata
    - name: List file Post
      run: ls -lah