name: File download test

permissions:
  actions: read
  contents: read

on:
  workflow_run:
    workflows: ["File test"]
    types:
      - completed

jobs:
  CreateFile:
    runs-on: ubuntu-latest
    steps:
    - name: List artifacts (debug)
      run: gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: List file Pre
      run: ls -lah
    - uses: actions/download-artifact@v4
    - name: List file Post
      run: ls -lah
    - name: Install GitHub CLI
      uses: cli/cli-action@v2
    - name: Download artifact zip from triggering run
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api \
          repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts \
          --jq '.artifacts[] | select(.name == "mydata") | .archive_download_url' \
        | xargs -n1 curl -L -H "Authorization: token $GH_TOKEN" -o mydata.zip
    - name: Unzip artifact
      run: unzip mydata.zip